language: python
python:
- "2.7"
- "3.4"
os: linux
env:
  - BUILD_TOOL=scons"
  - BUILD_TOOL=autotools"

matrix:
  include:
  - os: osx
    language: generic
    env: BUILD_TOOL=scons
  - os: osx
    language: generic
    env: BUILD_TOOL=autotools

sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libsdl2-dev
      - scons

before_install:
- source build/.travis/before_install.sh

install:
- source build/.travis/install.sh

before_script:
- pip install pytest pytest-cov
- (cd python && python setup.py develop)

script:
- 'if [[ "$BUILD_TOOL" == "autotools" ]]; then echo "#include <libtcod.h>" | gcc -xc -c -I$HOME/.local/include/libtcod -; fi'
- 'if [[ "$BUILD_TOOL" == "autotools" ]]; then echo "#include <libtcod.hpp>" | gcc -xc++ -c -I$HOME/.local/include/libtcod -; fi'
- 'if [[ "$BUILD_TOOL" == "autotools" ]]; then (cd build/autotools && make check); fi'
- 'if [[ "$BUILD_TOOL" == "scons" ]]; then LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR ./unittest; fi'
- (cd python && pytest -v)
